//! Inbox item model
//!
//! Represents candidate knowledge items generated by agents or imported content.
//! Inbox items flow through a triage process before becoming promoted to knowledge.

use chrono::Utc;
use serde::{Deserialize, Serialize};

/// Source type for an inbox item.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InboxSourceType {
    /// Generated by an AI agent during a session
    Agent,
    /// Imported from external sources (web clip, file import, etc.)
    Import,
    /// Pasted directly by the user
    Paste,
    /// Manually created by the user
    Manual,
    /// Generated by reliability/quality monitoring system
    Reliability,
}

/// Status of an inbox item in the triage workflow.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InboxStatus {
    /// Newly created, awaiting review
    New,
    /// Reviewed, ready for drafting
    Triaged,
    /// A draft has been created from this item
    Drafted,
    /// Successfully promoted to knowledge
    Promoted,
    /// Dismissed/ignored (soft terminal state, can be restored)
    Ignored,
}

/// Represents a candidate knowledge item in the inbox.
///
/// Inbox items are temporary staging objects that may be promoted to
/// full knowledge entries through a review and drafting process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InboxItem {
    /// Unique identifier (ULID format)
    pub id: String,

    /// Source type of this item
    pub source_type: InboxSourceType,

    /// Name of the agent that generated this item (if applicable)
    pub source_agent: Option<String>,

    /// Candidate title for the knowledge entry
    pub title: String,

    /// Candidate summary snippet
    pub snippet: Option<String>,

    /// Full candidate content in markdown format
    pub content_markdown: Option<String>,

    /// Suggested path for where this should be stored
    pub proposed_path: Option<String>,

    /// Current status in the triage workflow
    pub status: InboxStatus,

    /// ID of the draft created from this item (if any)
    pub linked_draft_id: Option<String>,

    /// ID of the session that created this item (if any)
    pub linked_session_id: Option<String>,

    /// Path to the knowledge entry this was promoted to (if any)
    pub linked_knowledge_path: Option<String>,

    /// Additional metadata for extensibility
    pub metadata: serde_json::Value,

    /// When this item was created
    pub created_at: String,

    /// When this item was last updated
    pub updated_at: String,
}

impl InboxItem {
    /// Create a new inbox item with required fields.
    pub fn new(source_type: InboxSourceType, title: String) -> Self {
        let now = Utc::now().to_rfc3339();
        Self {
            id: ulid::Ulid::new().to_string(),
            source_type,
            source_agent: None,
            title,
            snippet: None,
            content_markdown: None,
            proposed_path: None,
            status: InboxStatus::New,
            linked_draft_id: None,
            linked_session_id: None,
            linked_knowledge_path: None,
            metadata: serde_json::json!({}),
            created_at: now.clone(),
            updated_at: now,
        }
    }

    /// Validate if a status transition is allowed.
    pub fn can_transition_to(&self, new_status: &InboxStatus) -> bool {
        match (&self.status, new_status) {
            // Normal flow: new -> triaged -> drafted -> promoted
            (InboxStatus::New, InboxStatus::Triaged) => true,
            // Sprint 1 UX allows direct draft creation from a fresh inbox item
            (InboxStatus::New, InboxStatus::Drafted) => true,
            (InboxStatus::Triaged, InboxStatus::Drafted) => true,
            (InboxStatus::Drafted, InboxStatus::Promoted) => true,

            // Any state can transition to ignored
            (_, InboxStatus::Ignored) => true,

            // Ignored can be restored to triaged
            (InboxStatus::Ignored, InboxStatus::Triaged) => true,

            // Self-transition (no-op)
            (current, new) if current == new => true,

            // All other transitions are invalid
            _ => false,
        }
    }

    /// Update the timestamp to current time.
    pub fn touch(&mut self) {
        self.updated_at = Utc::now().to_rfc3339();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_new_inbox_item() {
        let item = InboxItem::new(InboxSourceType::Agent, "Test Title".to_string());

        assert!(item.id.len() > 0);
        assert_eq!(item.source_type, InboxSourceType::Agent);
        assert_eq!(item.title, "Test Title");
        assert_eq!(item.status, InboxStatus::New);
        assert!(item.source_agent.is_none());
        assert!(item.snippet.is_none());
        assert!(item.content_markdown.is_none());
        assert!(item.proposed_path.is_none());
        assert!(item.linked_draft_id.is_none());
        assert!(item.linked_session_id.is_none());
        assert!(item.linked_knowledge_path.is_none());
    }

    #[test]
    fn test_valid_transitions() {
        let mut item = InboxItem::new(InboxSourceType::Manual, "Test".to_string());

        // new -> triaged
        assert!(item.can_transition_to(&InboxStatus::Triaged));

        // new -> drafted is also allowed for direct agent workflow
        assert!(item.can_transition_to(&InboxStatus::Drafted));
        item.status = InboxStatus::Triaged;

        // triaged -> drafted
        assert!(item.can_transition_to(&InboxStatus::Drafted));
        item.status = InboxStatus::Drafted;

        // drafted -> promoted
        assert!(item.can_transition_to(&InboxStatus::Promoted));
    }

    #[test]
    fn test_ignore_transition() {
        let mut item = InboxItem::new(InboxSourceType::Import, "Test".to_string());

        // Any state can transition to ignored
        assert!(item.can_transition_to(&InboxStatus::Ignored));
        item.status = InboxStatus::Ignored;

        // Ignored can be restored to triaged
        assert!(item.can_transition_to(&InboxStatus::Triaged));
    }

    #[test]
    fn test_invalid_transitions() {
        let item = InboxItem::new(InboxSourceType::Agent, "Test".to_string());

        // Direct drafting is allowed, but promotion still cannot skip ahead.
        assert!(item.can_transition_to(&InboxStatus::Drafted));
        assert!(!item.can_transition_to(&InboxStatus::Promoted));
    }

    #[test]
    fn test_touch_updates_timestamp() {
        let mut item = InboxItem::new(InboxSourceType::Paste, "Test".to_string());
        let original_updated = item.updated_at.clone();

        // Wait a tiny bit to ensure timestamp difference
        std::thread::sleep(std::time::Duration::from_millis(10));
        item.touch();

        assert_ne!(original_updated, item.updated_at);
    }
}
